### ISSUE TITLE
BlueprintsPersistenceBackend#createVertex(PersistentEObject) is not efficient

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#72]
This method delegates to IdGraph#addVertex(Object) that checks that the ID doesn't exist by iterating all the nodes in the database, and then creates the new element.

We can avoid this useless iteration (NeoEMF IDs are unique) by telling the backend it should not worry about ID uniqueness. `IdGraph#enforeUniqueIDs(boolean)` can help.

**Comment by yvernageau** [comment]
This behavior has been defined in the constructor of `AbstractBlueprintsBackend#InternalIdGraph`.

But we have to be careful: uniqueness cannot be guaranteed when creating a new `Id`.
However, the probability of collision is assumed to be very low ([UUID Collisions](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions))

We need to make sure that `EcoreUtil#generateUUID()` generates a valid UUID, because it looks shorter (and therefore less safe) than the result of `UUID.generate()`. According the the documentation, it generate a 128-bit UUID, it's maybe sufficient.
