### ISSUE TITLE
Guava compile/runtime issues

### ISSUE THREAD

**Issue by arcanefoam** [atlanmod/NeoEMF#74]
Not sure is completly related to NeoEMF but I am trying to use it in another project and at runtime I am getting a (from maven test):
`"com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;" type="java.lang.NoSuchMethodError">java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)`

A google search seems to indicate that the compile signature of the checkNotNull method is different from the runtime signature. 
My parent project uses guava 18, which is the same as the one the bluprints data module uses (v. 1.0.1).

**Comment by gdaniel** [comment]
Hi Horacio,

I just checked the pom we use in NeoEMF 1.0.1 (https://github.com/atlanmod/NeoEMF/blob/v1.0.1/pom.xml): the guava version used into all the projects is 20, so your issue may be related to that.

Where did you find the guava version? I remember we were using 18 before, so there is maybe a dependency we forgot.

Anyway this should not be an issue anymore in the next releases: we have removed the guava dependency because it creates many conflicts with existing applications.

**Comment by arcanefoam** [comment]
It turns our NeoEMF 1.0.1 Ships with Guava 20. Updating my project to the correct dependency fixed the issue.

**Comment by gdaniel** [comment]
Glad to hear it!
If you experience any issue when using NeoEMF don't hesitate to contact us.

**Comment by arcanefoam** [comment]
+1 On removing guava. I was about to open another ticket to discuss it was really needed :O

**Comment by gdaniel** [comment]
I personally think Guava is a good thing: it helped us a lot to improve the code quality and robustness of NeoEMF. But the API changes too often, and creates too much conflicts with existing applications. We had a bad time because of that when we tried to integrate EMF Compare and NeoEMF, and we decided to replace it with internal methods.

Next release should be available in few weeks.
