### ISSUE TITLE
Example with modisco replaces actual model

### ISSUE THREAD

**Issue by fcostasilva** [atlanmod/NeoEMF#83]
It turns out that the example project doesn't use the actual modisco java model, but a model that ressembles it instead. Why is this approach necessary?

**Comment by gdaniel** [comment]
Hi,

The example uses the same java metamodel as the one contained in MoDisco, but a different generated code. We use a NeoEMF-specific genmodel (NeoEMF importer), that changes the root element type from `EObject` to `PersistentEObject`, and enables reflective delegation.

This is currently needed because NeoEMF doesn't handle standard generated code (using the default Ecore importer). The infrastructure to support it is ready, but implementing it requires some time and we haven't done it yet. Unfortunately I cannot commit on any schedule for this feature, but this is definitely something we want to support.

**Comment by fcostasilva** [comment]
I've tried using a customized modisco's genmodel in a different project and NeoEMF worked as expected.

**Comment by gdaniel** [comment]
Glad to ear that NeoEMF is working as expected for you! If you have any trouble to make it fit your use case don't hesitate to contact us again.
