### ISSUE TITLE
Feature maps are not supported

### ISSUE THREAD

**Issue by yvernageau** [atlanmod/NeoEMF#84]
Feature maps are not properly supported: the code supposed to detect and create them doesn't exist in `DefaultPersistentEObject#dynamicGet(int)`

**Comment by yvernageau** [comment]
Fixed in #69

**Comment by yvernageau** [comment]
Serialize a `FeatureMap$Entry` with `EcoreUtil#convertToString` leads to an `IllegalArgumentException`.
`FeatureMap$Entry` are not simple values, but K/V pairs of a `EStructuralFeature` and its associated value, that can be either a simple value or a model object. The current mapping is not sufficient to support them and requires a pre-process to store values that are not processed in a common way : there is no call to `StoreAdapter` for model objects, so the containers and the metaclasses are not stored.

**Comment by yvernageau** [comment]
d7de3e4483b6ba3b2f2872fb498c51f483d6924c: The simplest and most efficient method seems to be a simple transformation of the `FeatureMap.Entry` into its representation as a formatted string (`featureName#value`).
Pre/post-processing would require much more database calls because of the `FeatureMap` structure.

**Comment by paulreuter** [comment]
I have just tried to load a model in which the DocumentRoot content is stored in a feature map. 

Unfortunately, the dynamicGet of DefaultPersistentEObject does not get called; the eGet method of BasicEObjectImpl calls the dynamicGet method of eSettingDelegate(eFeature) instead of its own. 

This results in a ClassCastException: fr.inria.atlanmod.neoemf.core.DefaultPersistentEObject$EStoreEcoreEList cannot be cast to org.eclipse.emf.ecore.util.FeatureMap$Internal

Is this something that can be fixed by tweaking model generation, or is some modification to NeoEMF classes necessary?

**Comment by sunye** [comment]
Hi Paul,

Version 1.0.2 doesn't handle FeatureMaps. However, the current code on branch "master" solves this issue. 

Regards,

**Comment by paulreuter** [comment]
Hello Gerson,

many thanks for your reply, but this issue was with the code from the snapshot update site, plugin version of 1.0.3.20180215194203
I am guessing that this is much closer to master than 1.02, is it? Or do I need to build from Git for these changes?

Kind regards,
Paul

**Comment by sunye** [comment]
Paul,

We did a big merge yesterday, the snapshot you have is 1 day too old. Please try again with the current snapshot.
