### ISSUE TITLE
Update to Neo4j 3.3.1

### ISSUE THREAD

**Issue by flagadajones** [atlanmod/NeoEMF#86]
hi,
Is it possible to update backend to neo4j 3.2 ?
when i try to open database  i get  this error :

Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@56d97dcf' was successfully initialized, but failed to start. Please see the attached cause exception "Not possible to upgrade a store with version 'v0.A.0' to current store version `v0.A.8` (Neo4j 3.2.6).".

**Comment by gdaniel** [comment]
Hi,

This is something we'd like to do, and it is definitely on top of our todo list. However, I cannot provide any information about this integration. This require a little bit of work because upgrading the Neo4j version also implies to upgrade the Blueprints version we are using, that provides a different API than the one we currently rely on.

I'll post in this thread any news regarding Neo4j 3.x integration.

Gwendal
